### ISSUE TITLE
Wrong chapter number at 3.1

### ISSUE THREAD

**Issue by et1421** [jaipandya/SublimeTutor#12]
In the end of chapter 3.1, it tells us to go to chapter 3.1. It should tell us to go to chapter 3.2

> Let's go to the next chapter chapter_3_1.md which will introduce us to column
> selection techniques.

**Comment by jaipandya** [comment]
Hi @et1421, the issue was fixed with a PR by @yusucan yesterday: https://github.com/jaipandya/SublimeTutor/pull/11 Your code will be automatically updated when you restart Sublime Text. (It pulls the latest code from Package Control every time it starts)

I'm closing this issue for now. If you continue to face this issue, please let me know.
