### ISSUE TITLE
Wrong sorting of chapters

### ISSUE THREAD

**Issue by dymv** [jaipandya/SublimeTutor#16]
Hey! Right now it goes like this:

```
chapter_1.md
chapter_2.md
chapter_2_1.md
chapter_2_10.md
...
```

Note that 10 comes after 1, which is incorrect (seems like Sublime is not using numeric sorting of files).
What do you think about adding leading zeroes to fix it and make it like that?

```
chapter_01.md
chapter_02.md
chapter_02_01.md
chapter_02_02.md
chapter_02_03.md
...
chapter_02_10.md
...
```

**Comment by jaipandya** [comment]
Hi @dymv. I understand your point, but given that I specifically ask to use `Goto anything` shortcuts for navigation from one chapter to another, I thought this would be of little consequence. Yes, I want the user to use shortcut instead of clicking on a filename in the sidebar for navigation. Do you still think changing the naming scheme would be beneficial here?
