### ISSUE TITLE
2_12 error?

### ISSUE THREAD

**Issue by ajlowndes** [jaipandya/SublimeTutor#19]
On my macbook air w/ SublimeText 3114, `CMD+/` just comments the line repeatedly instead of toggling commenting. If I press `CMD+/` 4 times on that third line in the html code, I end up with:

`<!-- <!-- <!-- <!-- <li>third list item</li> --> --> --> -->`

**Comment by jaipandya** [comment]
I can't tell you the reason here, but this is how it works for me. If you are not able to solve the issue yourself, you can try asking this question on [Sublime Text forums](https://forum.sublimetext.com/c/technical-support).

![issue_19](https://cloud.githubusercontent.com/assets/193139/16000528/80659146-316a-11e6-8b25-863d9f2248ce.gif)

**Comment by jaipandya** [comment]
I'm closing the issue after non-activity.
