### ISSUE TITLE
chapter_5_3.mg Replace Next in the Exercise

### ISSUE THREAD

**Issue by smileleaf** [jaipandya/SublimeTutor#41]
Hi

Thanks for the very useful tutorial.

#### typo in 5_3 for WIndows:
I am working on Windows 10. In chapter_5_3, in the Exercise at the end (point 6, line 72) it mentions the shortcut to replace next is `Ctrl + Shift + E` while it should be `Ctrl + Shift + H`. I saw the source file reflecting this correctly for Mac, so I think it is rendered wrong for Windows,

#### Some minor comments about 5_2:
1.
 For 5_2 I would like to suggest an addition to the end of the third paragraph (the one starting at line 14: These commands...): 
 "regular find `Esc` key plays that role"*while here it just exit the panel without moving the cursor.*

2.
 I know it is explained in the Exercise, But I feel it should be explained in the start clearly that Ctrl + I opens the panel first time it is pressed:
```
Let's learn the shortcuts first:

* Incremental find panes - `Ctrl + I` 
* Incremental find next  - `Ctrl + I` (While panel is open)
* Incremental find previous - `Ctrl + Shift + I`
```
3.
 And maybe mention that Ctrl + E works much better with regular Find.

Thanks

**Comment by jaipandya** [comment]
Thanks for suggesting the fixes. They have been added to the repository through https://github.com/jaipandya/SublimeTutor/commit/a4c46d9a2ef6f6cdcd613f384b8727a977a8e97f and https://github.com/jaipandya/SublimeTutor/commit/abf41acca0e623db86b6eed648364cb06b108802.

About chapter 5_2, some of the decisions were intentional as I didn't want to confuse the reader. As a result skipped the instructions related to <kbd>Esc</kbd> key there.
